npmScopes:
  # nju33:
  #   npmRegistryServer: https://npm.pkg.github.com/
  #   npmPublishRegistry: https://npm.pkg.github.com/
  #   npmAuthToken: ${GH_AUTHTOKEN}
  #   npmAlwaysAuth: true
  bit:
    npmRegistryServer: https://node.bit.cloud
    npmAuthToken: ${BIT_TOKEN}
    npmAlwaysAuth: true
  aryli:
    npmRegistryServer: https://node.bit.cloud
    npmAuthToken: ${BIT_TOKEN}
    npmAlwaysAuth: true
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: ${FONT_AWESOME_PACKAGE_TOKEN}
    npmAlwaysAuth: true
