npmScopes:
  # nju33:
  #   npmRegistryServer: //npm.pkg.github.com/
  #   npmAuthToken: ${GH_AUTHTOKEN}
  #   npmAlwaysAuth: true
  bit:
    npmRegistryServer: https://node.bit.cloud
    npmAuthToken: ${BIT_TOKEN}
    npmAlwaysAuth: true
  aryli:
    npmRegistryServer: https://node.bit.cloud
    npmAuthToken: ${BIT_TOKEN}
    npmAlwaysAuth: true
