on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: 0.0.1-11
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nju33/gitpod-workspace
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - run: echo "FROM nju33/gitpod-workspace:$IMAGE_VERSION" > .gitpod.Dockerfile
      - run: |
          git config --local user.name "github-actions[bot] "
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .gitpod.Dockerfile
          git commit -m "chore(github-actions): bump version to $IMAGE_VERSION"
          git push origin main
          