name: Docker push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VALUE }}
    env:
      IMAGE_NAME: nju33/gitpod-workspace
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}

      - name: Set version
        run: echo "::set-output name=VALUE::${GITHUB_REF#refs/tags/v}"
        id: version

      - name: Login to Dockerhub
        run: echo "$DOCKER_TOKEN" | docker login --username nju33 --password-stdin
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Dockerfile
        run: docker build -t "$IMAGE_NAME" .
      - run: |
          docker image tag "$IMAGE_NAME" "$IMAGE_NAME:$VERSION"
          docker image push "$IMAGE_NAME:$VERSION"
        env:
          VERSION: ${{ steps.version.outputs.VALUE }}

  dispatch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          curl -i -XPOST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/nju33/gitpod-workspace/dispatches \
            -d "{\"event_type\":\"updated_docker_image\",\"client_payload\":{\"image\":\"$VERSION\"}}"
        env:
          TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          VERSION: ${{ needs.build.outputs.VERSION }}