name: Docker push

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VALUE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set version
        run: echo "::set-output name=VALUE::${GITHUB_REF#refs/tags/v}"
        id: version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "nju33"
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "nju33/gitpod-workspace:${{ steps.version.outputs.VALUE }}"

  dispatch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          curl -i -XPOST \
            -H "Authorization: Bearer $TOKEN" \
            "$REPOSITORY_DISPATCH_DELEGATION" \
            -d "{\"event_type\":\"updated_docker_image\",\"client_payload\":{\"image\":\"$VERSION\"}}"
        env:
          REPOSITORY_DISPATCH_DELEGATION: ${{ secrets.REPOSITORY_DISPATCH_DELEGATION }}
          TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          VERSION: ${{ needs.build.outputs.VERSION }}
