name: Push

on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -i -XPOST \
            -H "Authorization: Bearer $TOKEN" \
            "$REPOSITORY_DISPATCH_DELEGATION" \
            -d "{\"event_type\":\"updated_gitpod_repo\",\"client_payload\":{}}"
        env:
          REPOSITORY_DISPATCH_DELEGATION: ${{ secrets.REPOSITORY_DISPATCH_DELEGATION }}
          TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}